### ISSUE TITLE
Move to Fastify org?

### ISSUE THREAD

**Issue by jsumners** [fastify/avvio#109]
Should this repo be moved to the Fastify org? It provides a significant portion of Fastify's core and routinely has to be updated to resolve issues in Fastify. Also, was it not written specifically to make Fastify possible?

**Comment by mcollina** [comment]
I started writing this before Fastify existed. To some extent avvio is what https://github.com/senecajs/seneca/pull/402 never got to become.

However I think it make sense to move this to Fastify org as it's the main usecase right now.

@delvedor any objections? I think the only 2 remaining pieces are avvio and find-my-way.

**Comment by delvedor** [comment]
If you are ok with I see no problem in moving it into the Fastofy org, as Fastify is the only real customer of avvio.

I'll think about `find-my-way`, as it's not only used by Fastify, but also by Restify and many route libraries for Koa or Micro.

**Comment by mcollina** [comment]
Done closing.

**Comment by jsumners** [comment]
> I'll think about find-my-way, as it's not only used by Fastify, but also by Restify and many route libraries for Koa or Micro.

In my opinion, that doesn't matter. Fastify the org can maintain generic libraries such as `avvio` and `find-my-way`. By being the primary user of those generic modules it will find the edge cases and missing features necessary to make those generic modules even more useful to the community as a whole.

**Comment by bugagashenkj** [comment]
@delvedor @mcollina What about this issue. Should we move find-my-way to the Fistify org, or should we close this issue?
