### ISSUE TITLE
override function not throw errors 

### ISSUE THREAD

**Issue by zhangwinning** [fastify/avvio#119]
## 🐛 Bug Report

override callback function not throw errors 

## To Reproduce

invoke the below code, not throw errors 

```js
// Paste your code here
const boot = require('avvio');

const server = {my: 'server'};

const app = boot(server);

app.override = function (s, fn) {
    error;
    return s;
};

app.use(first);

function first(s, opts, cb) {
    cb();
}


```

## Expected behavior

should throw error 
```js
ReferenceError: error is not defined
```

## Your Environment

- *node version*: v12.14.0
- *fastify version*: >=2.0.0
- *os*: Mac
- *any other relevant information*

**Comment by Eomm** [comment]
You need to manage the error:

```
app.use(first)
  .ready(e => {
    console.log(`The error is ${e.message}`)
  })
```

**Comment by zhangwinning** [comment]
thanks, I got it
