### ISSUE TITLE
Make Fastify plugins interoperable with Avvio

### ISSUE THREAD

**Issue by paulorodrigues-mb** [fastify/avvio#168]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

My proposal is to make Fastify plugins interoperable with Avvio for cases when I need to share the same resources (plugins) with another process without need to handle HTTP requests.

### Motivation

A common pattern for developing backend applications is to have 2 distinct processes one for handle http requests and another to do background tasks, a worker process.

Fastity is really great to handle HTTP requests and more than that, the plugin ecosystem is awesome and starting a robust application is a nice experience.

But the thing gets complicated when need to share plugins (resources) with another process for example to accomplish the pattern above described for background job processing.

Once the plugin system is very opinionated and tied to Fastify HTTP lifecycle it turns very difficult to share those resources.

### Example

For example today I have an application with 2 entry points:

1. `api.js` instantiate a Fastity instance and start listening for http requests
2. `worker.js` instantiate a Fastity instance too but instead of listening for http requests it is waiting for consume amqp messages.

Both processes lives on the same project and my intention is both share the same resource/plugins.

The code of worker.js looks like this:

```javascript
const Fastify = require('fastify')
const Autoload = require('fastify-autoload')
const closeWithGrace = require('close-with-grace')

const { join } = require('path')
const amqp = require('amqplib')

const server = Fastify({ logger: true })

;(async function () {
  closeWithGrace({ delay: 500 }, async function ({ err }) {
    if (err) {
      server.log.error(err)
    }
  })

  server.register(Autoload, {
    dir: join(__dirname, 'plugins')
  })

  await server.after()
  
  server.register(Autoload, {
    dir: join(__dirname, 'tasks')
  })

  await server.after()
  
  server.register(async function (server, opts) {
    const conn = await amqp.connect(server.config.RABBITMQ_CONNECTION_STRING)
    const channel = await conn.createChannel()
  
    await channel.assertExchange(server.config.PORTAL_EXCHANGE, 'topic')
    await channel.assertQueue(server.config.PORTAL_QUEUE)

    await channel.bindQueue(server.config.PORTAL_QUEUE, server.config.PORTAL_EXCHANGE, '*.*')

    async function onMessage (message) {
      const { fields: { routingKey }, content } = message
      
      let param

      try {
        param = JSON.parse(content)
      } catch (err) {
        param = content.toString()
      }

      const taskFn = server[routingKey]

      if (!taskFn) {
        server.log.error(`Task not found: ${routingKey}`)
        return
      }
      
      try {
        await taskFn(param)
      } catch (err) {
        channel.nack(message)
        server.log.error({ err }, `Unable to process task: ${routingKey}`)
      }
    }

    channel.consume(server.config.PORTAL_QUEUE, onMessage, { noAck: true })

    conn.on('close', function () {
      server.log.error(`Connection lost with ${server.config.RABBITMQ_CONNECTION_STRING}`)
      process.exit(1)
    })

    conn.on('error', function (err) {
      server.log.error(err)
      process.exit(1)
    })
  })

  await server.ready()

  server.log.info('Worker is ready and waiting for messages.')
})()
```

It does the job, but as highlighted from @jsumners doesn´t make sense to have a HTTP server without listening to HTTP requests and I have to agree with that.

**Comment by jsumners** [comment]
This is a generic module for adding plugin capabilities to your application. Fastify uses it as such. We will not be reimplementing the Fastify API in this module.
