### ISSUE TITLE
Sync loading?

### ISSUE THREAD

**Issue by Uzlopak** [fastify/avvio#195]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Is there any way that I could propose a way to sync load plugins?
detecting the number of parameters of the pluign function (3 === callbackPlugin) or checking if the function is async (like I implemented it [here](https://github.com/Automattic/mongoose/blob/94d96b87bb2ede11005069483a9be85c16a88726/lib/helpers/isAsyncFunction.js) should be a good enough to determine that an non async function with 2 parameters is a sync function?!

Maybe add symbol to check if the method is a sync Function so when we load the plugin we check if syncSymbolKey is true and load it sync instead of async? 

### Motivation

I want to load some specific plugins sync. now i have to await it to ensure it is loaded when I want to add the next plugin

**Comment by kibertoad** [comment]
Maybe there could be a separate method for that? Polymorphic magic adds significant complexity.

**Comment by Uzlopak** [comment]
Creating a registerSync method in fastify feels kind lf odd.

**Comment by kibertoad** [comment]
What's odd about it, if behaviour is different?

**Comment by Uzlopak** [comment]
Before that gets approved i assume an await is easier.

**Comment by voxpelli** [comment]
> now i have to await it to ensure it is loaded when I want to add the next plugin

What's the problem you see in doing this?

**Comment by kibertoad** [comment]
"easier" is a subjective concept. The fact that it requires less code doesn't mean that it doesn't also increase cognitive complexity of said code. If there are two wildly different branches possible for very similar code, that reduces predictability of the said code.

**Comment by mcollina** [comment]
It's _impossible_ to load a plugin synchronously because there can be more than one asynchronous plugin being loaded.
