### ISSUE TITLE
Updating for v5

### ISSUE THREAD

**Issue by nrayburn-tech** [fastify/avvio#245]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I'm looking to update this repo for v5. https://github.com/fastify/fastify/issues/5116

Changes Needed (Please let me know if anything might be missing)

- Update workflows to use v4
- Update dependencies

**Comment by Fdawgs** [comment]
Closed by https://github.com/fastify/avvio/pull/246
