### ISSUE TITLE
Broken tests

### ISSUE THREAD

**Issue by mcollina** [fastify/avvio#249]
Currently the tests on master fails.

**Comment by Uzlopak** [comment]
Pinned down the breaking to release of fastq v1.17.0.  Last working with fastq v1.16.0

**Comment by climba03003** [comment]
I would say that the test is not broken, but `fastq` shipped breaking change in `minor`.

**Comment by mcollina** [comment]
https://github.com/mcollina/fastq/pull/81 didn't look breaking at all.

**Comment by mcollina** [comment]
Confirmed it breaks avvio somehow. Essentially the `.ready()` method is not called.

**Comment by climba03003** [comment]
It changed the test a lot, so it does not guarantee nothing is not broken.

**Comment by mcollina** [comment]
Found the bug, PR incopming

**Comment by Uzlopak** [comment]
Yep. The tests pass now.
